# 公共配置文件
spring:
  application:
    name: community-user
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  # Springfox使用的路径匹配是基于AntPathMatcher的，
  #而Spring Boot 2.6.X使用的是PathPatternMatcher。
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      # 大小限制
      max-file-size: 50MB
      max-request-size: 50MB
  # 数据库配置
  # todo 需替换配置
  datasource:
    # 数据库访问配置, 使用druid数据源(默认数据源是HikariDataSource)
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clearly_understand?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456
    # 初始连接数
    initialSize: 5
    # 最小连接池数量
    minIdle: 10
    # 最大连接池数量
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 配置一个连接在池中最大生存的时间，单位是毫秒
    maxEvictableIdleTimeMillis: 900000
    # 配置检测连接是否有效
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    webStatFilter:
      enabled: true
    statViewServlet:
      enabled: true
      # 设置白名单，不填则允许所有访问
      allow:
      url-pattern: /druid/*
    filter:
      stat:
        enabled: true
        # 慢SQL记录
        log-slow-sql: true
        slow-sql-millis: 1000
        merge-sql: true
      wall:
        config:
          multi-statement-allow: true

    # Druid监控配置
    druid:
      webStatFilter:
        enabled: true
        urlPattern: /druid/*
      statViewServlet:
        enabled: true
        allow:
        loginUsername: admin
        loginPassword: admin

  #Redis 配置
  #todo 需替换配置，然后取消注释
  redis:
    host: localhost
    port: 6379
    timeout: 5000
    lettuce:
      pool: #连接池配置
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
  #  elasticsearch:
  #    uris: http://localhost:9200
  #    username: root
  #    password: 123456

server:
  port: 8101
  servlet:
    context-path: /api
  tomcat:
    max-swallow-size: 100MB


# 对象存储
# todo 需替换配置
minio:
  endpoint: http://localhost:9000 #Minio服务所在地址
  bucketName: testbucket #存储桶名称
  accessKey: wX9LDd5urmXBHfclzh5B #访问的key
  secretKey: nrYvLpfPSeqzbBzPWbBJFRnqiUyy5Prn3vFQKGtd #访问的秘钥

jwt:
  config:
    key: picacho
    ttl: 600000
    remember: 604800000

# mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: ASSIGN_ID # 全局唯一ID生成策略：雪花算法
      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
  configuration:
    map-underscore-to-camel-case: true
    AutoMappingUnknownColumnBehavior: WARNING
    auto-mapping-behaviot: full
    #      # 配置别名
    #      type-aliases-package: com.xsge.app.entity
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# knife4j
knife4j:
  swagger:
    enabled: true

custom:
  config:
    ignores:
      # 需要过滤的 post 请求
      post:
      # 需要过滤的请求，不限方法
      pattern:
        - "/auth/login"
        - "/loginLog/page"
        - "/test/*"
        - "/doc.html"
        - "/webjars/**"
        - "/swagger-resources/**"
        - "/v2/api-docs"
        - "/druid/**"